databases:
  - name: kotomoku_DB
    databaseName: kotomoku_db
    user: kotomoku
    region: singapore

services:
  - type: web
    name: kotomoku
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kotomoku
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

